#!/usr/bin/env bash

source "${LIB_PATH}"

run_path() {
    info "Path" "Reconciling critical paths..."

    local path_file="${TARGET_HOME}/.devcontainer.profile_path"
    
    local paths_to_add=(
        "${TARGET_HOME}/.local/bin"
        "${TARGET_HOME}/go/bin"
        "${TARGET_HOME}/.cargo/bin"
        "/usr/local/go/bin"
        "/usr/local/cargo/bin"
        "/usr/games"
    )

    # Scan /usr/local and /opt for 'bin' directories
    while IFS= read -r dir; do
        paths_to_add+=("$dir")
    done < <(find /usr/local /opt -maxdepth 3 -type d -name bin 2>/dev/null | grep -vE "^/usr/local/bin$|^/usr/bin$|^/bin$" || true)

    # Scan $HOME for 'bin' directories (e.g. Ruby gems, Python, Go, etc)
    # Broaden filter to ensure we don't miss language-specific folders
    while IFS= read -r dir; do
        paths_to_add+=("$dir")
    done < <(find "${TARGET_HOME}" -maxdepth 8 -type d -name bin 2>/dev/null | grep -E "gem|node|python|\.local|npm|go|cargo|yarn|rbenv|rvm" || true)

    echo "# Generated by devcontainer-profile" > "${path_file}.tmp"
    declare -A seen
    for p in "${paths_to_add[@]}"; do
        if [[ -z "${seen[$p]-}" ]]; then
            echo "case \":\$PATH:\" in *\":$p:\"*) ;; *) export PATH=\"\$PATH:$p\" ;; esac" >> "${path_file}.tmp"
            seen["$p"]=1
        fi
    done
    mv "${path_file}.tmp" "${path_file}"

    local source_cmd="[ -f \"${path_file}\" ] && . \"${path_file}\""
    update_file_idempotent "${TARGET_HOME}/.bashrc" "PROFILE_PATH" "$source_cmd"
    update_file_idempotent "${TARGET_HOME}/.zshrc" "PROFILE_PATH" "$source_cmd"
}

run_path
