#!/usr/bin/env bash

# Plugin: Path
# Reconciles environment PATH

reconcile_path() {
    info "[Path] Reconciling..."
    
    local path_file="${TARGET_HOME}/.devcontainer_profile_path"
    
    # 1. Collect Paths
    local paths_to_add=()
    
    # Standard OCI/Container paths
    local candidates=(
        "$HOME/.local/bin"
        "$HOME/go/bin"
        "$HOME/.cargo/bin"
        "/usr/local/go/bin"
        "/usr/local/cargo/bin"
        "/usr/games"
    )
    
    for p in "${candidates[@]}"; do
        if [[ -d "$p" ]]; then paths_to_add+=("$p"); fi
    done

    # Dynamic discovery (limited depth)
    while read -r dir; do
        paths_to_add+=("$dir")
    done < <(find /usr/local -maxdepth 3 -type d -name bin 2>/dev/null)

    # 2. Write the path file
    {
        echo "# Generated by devcontainer-profile"
        echo "add_path() { case \":\$PATH:\" in *\":\$1:\"*) ;; *) export PATH=\"\$PATH:\$1\" ;; esac; }"
        for p in "${paths_to_add[@]}"; do
            echo "add_path \"$p\""
        done
        echo "unset -f add_path"
    } > "$path_file"

    # 3. Hook into shells (Idempotent)
    local source_cmd="[ -f \"$path_file\" ] && . \"$path_file\""
    
    safe_append_if_missing ".devcontainer_profile_path" "$HOME/.bashrc" "$source_cmd"
    
    if [[ -f "$HOME/.zshrc" ]]; then
        safe_append_if_missing ".devcontainer_profile_path" "$HOME/.zshrc" "$source_cmd"
    fi
}

reconcile_path