#!/bin/bash

env_variables() {
    local env_file="${HOME}/.devcontainer.profile_env"
    
    local env_entries
    env_entries=$(jq -r '.env | to_entries[]? | "export \(.key)=\"\(.value | tostring)\""' "${USER_CONFIG_PATH}" 2>/dev/null)

    [[ -z "${env_entries}" ]] && return

    info "[Env] Reconciling environment variables..."

    echo "# Generated by .devcontainer.profile" > "${env_file}.tmp"
    echo "${env_entries}" >> "${env_file}.tmp"
    mv "${env_file}.tmp" "${env_file}"

    local source_cmd="\n# .devcontainer.profile env variables\n[ -f \"${env_file}\" ] && . \"${env_file}\"\n"

    if [[ -f "${HOME}/.bashrc" ]] && ! grep -qF "${env_file}" "${HOME}/.bashrc"; then
        echo -e "$source_cmd" >> "${HOME}/.bashrc"
    fi

    if [[ -f "${HOME}/.zshrc" ]] && ! grep -qF "${env_file}" "${HOME}/.zshrc"; then
        echo -e "$source_cmd" >> "${HOME}/.zshrc"
    fi

    # Export for the CURRENT script session so subsequent plugins see them
    # We source the file we just created to ensure correct escaping is handled by the shell
    if [[ -f "${env_file}" ]]; then
        # Use a subshell-safe method to export variables to the current process
        set -o allexport
        # shellcheck source=/dev/null
        source "${env_file}"
        set +o allexport
    fi
}

env_variables
