#!/usr/bin/env bash

source "${LIB_PATH}"

run_env() {
    local env_entries
    env_entries=$(jq -r '.env | to_entries[]? | "export \(.key)=\"\(.value | tostring)\""' "${USER_CONFIG_PATH}" 2>/dev/null)

    [[ -z "${env_entries}" ]] && return 0

    info "Env" "Applying environment variables..."

    local env_file="${TARGET_HOME}/.devcontainer.profile_env"
    
    echo "# Generated by devcontainer-profile" > "$env_file"
    echo "$env_entries" >> "$env_file"

    local source_cmd="[ -f \"${env_file}\" ] && set -a && . \"${env_file}\" && set +a"
    
    update_file_idempotent "${TARGET_HOME}/.bashrc" "PROFILE_ENV" "$source_cmd"
    update_file_idempotent "${TARGET_HOME}/.zshrc" "PROFILE_ENV" "$source_cmd"
}

run_env